#!/bin/bash

#Please read the edit_td_readme.txt for complete information 
#~author: Alexander Ramos Diaz.
# ~~~~~~You are FREE to use or adapt this code for your own project~~~~~~~~~

#~~~STEP 1: remove unnecessary lines in all .tab input files

echo
echo "Editing the following files:"
for filename in *.{txt,tab}
do
  #prints file list:
  echo $filename  
  #generates a new file name using the NCBI and species code only (selecting characters 1 to 11):
  newfilename=$(echo $filename | cut -c1-11) 
  #reads lines starting at position 2 and generates a new file with the data (this excludes first line):
  tail -n +2 $filename > $newfilename.aux
  #in the new auxiliary, file removes all lines that contain ERCC identifier that are control sequences and NOT actual organism's genes:
  sed -i '/ERCC/d' $newfilename.aux   
  #removes last five lines containing data set information:	
  head -n -5 $newfilename.aux > $newfilename.tmp
done
echo

#removes auxiliary .aux files
rm *.aux
  
#~~~STEP 2: calls timdataro.py which selects only overrepresented genes and edits the file in order to be suitable for hclust

python timdataro.py


#~~~STEP 3: removes empty lines generated by python (it is easier to remove them using bash) 

for updatedname in *.tmp
do
  #obtains NCBI + species code only: 
  finalname=$(echo $updatedname | cut -c1-11)
  #removes blank lines avoiding later reading mistakes in hclust:
  grep -v '^[[:blank:]]*$' $updatedname > $finalname.tsv
done

#removes auxiliary .tmp files and keeps only input .tab files (raw input) and .tsv (input files for hclust):
rm *.tmp

#~~~STEP 4: generates general information of the output and separated folders for raw data and edited data

#moces all updated files to a folder called edited_data
mkdir edited_data
echo "Updated files that can be used with hclust are:"
for finalfile in *.tsv
do
  echo $finalfile
  mv $finalfile edited_data
done
echo "Please open the edited_data folder to check updated time-course files."


#moves all tab files to a folder called raw_data:
mkdir raw_data
echo
for tabfile in *.{txt,tab}
do
 mv $tabfile raw_data
done  
echo "Raw time-course data moved to raw_data folder."
echo "File editing finished".
echo


#~~~~~~~~~~~~~~~end~~~~~~~~~~~~~~~~




		
